# Name of the workflow
name: Deploy to Cloud Run from Source

# This workflow gets triggered on push to the 'main' branch
on:
  push:
    branches: ["main"]

# Environment variables used in the workflow
env:
  PROJECT_ID: romodo-fleets
  SERVICE: fleet-manager
  REGION: asia-northeast2
  PUBLIC_BASE_PATH: "/"

# Jobs that the workflow will run
jobs:
  # Setup job
  setup:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

  # Build job
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step to install 'pack' (a tool for building apps using Buildpacks)
      - name: Install Pack
        run: |
          sudo wget https://github.com/buildpacks/pack/releases/download/v0.20.0/pack-v0.20.0-linux.tgz
          sudo tar xvfz pack-v0.20.0-linux.tgz -C /tmp
          sudo rm pack-v0.20.0-linux.tgz
          sudo mv /tmp/pack /usr/local/bin/pack
          pack version

      # Step to build and push Docker image
      - name: Build and Push Docker image
        run: |
          pack build gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest --path ./romodo-fleet-manager/ --builder heroku/buildpacks:20
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest

  # Deploy job
  deploy:
    # This job needs the 'build' job to complete successfully before it can run
    needs: build
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step to authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.1
        with:
          credentials_json: ${{ secrets.GCP_CRED_NEW }}

      # Step to install Google Cloud SDK
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Step to use gcloud CLI
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Step to deploy to Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2.2.0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest

      # Step to show the output (URL of the deployed service)
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}